ACCEPT NUM PROMPT '숫자입력 ?'
DECLARE
	--예외 선언
	EVEN_NUMBER EXCEPTION;
	
BEGIN
	IF MOD(&NUM,2) = 0 THEN
		RAISE EVEN_NUMBER;
	END IF;
	DBMS_OUTPUT.PUT_LINE(&NUM || '은 홀수');

	EXCEPTION
	WHEN EVEN_NUMBER THEN
		DBMS_OUTPUT.PUT_LINE('짝수는 안되요');
END;
/