ACCEPT ID PROMPT '아이디 입력?'

DECLARE
	NAME_ MEMBER.NAME%TYPE;
	ID_ MEMBER.ID%TYPE := '&ID';
BEGIN
	--SELECT ID INTO ID_ FROM MEMBER ;
	
	
	SELECT ID,NAME INTO ID_, NAME_
	FROM MEMBER
	WHERE ID = ID_;
	DBMS_OUTPUT.PUT_LINE('이름 : ' || NAME_ );
	DBMS_OUTPUT.PUT_LINE('아이디 : ' || ID_ );
	
	EXCEPTION
	/*
	WHEN TOO_MANY_ROWS THEN
		DBMS_OUTPUT.PUT_LINE('여러개의 레코드가 검색되었어요');
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE(ID_ || '로 검색된 회원이 없어요');
	*/
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('에러번호: ' || SQLCODE);
		DBMS_OUTPUT.PUT_LINE('에러메시지: ' || SQLERRM);
END;	
/