ACCEPT NUM PROMPT '숫자입력 ? '

DECLARE
	--변수 선언
	NUM_ VARCHAR2(20);
	--예외 선언
	NOT_NUMBER EXCEPTION;
	PRAGMA EXCEPTION_INIT( NOT_NUMBER, -01722 );	
BEGIN
	SELECT 10+ '&NUM' INTO NUM_
	FROM DUAL;
	DBMS_OUTPUT.PUT_LINE('당신의 10년후 나이: ' || NUM_ );

	EXCEPTION
	WHEN NOT_NUMBER THEN
		DBMS_OUTPUT.PUT_LINE('나이는 숫자만....');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('오류발생: '|| SQLERRM);
END;
/