BEGIN
	/*DBMS_OUTPUT.PUT('A');
	DBMS_OUTPUT.PUT('가');
	--DBMS_OUTPUT.PUT_LINE('새로운 라인');
	DBMS_OUTPUT.NEW_LINE;*/
	FOR I IN 1 .. 4 LOOP
		FOR J IN 1 .. 4 LOOP
			IF I = J THEN
				DBMS_OUTPUT.PUT('1  ');
			ELSE 
				DBMS_OUTPUT.PUT('0  ');
			END IF;
		END LOOP;
		DBMS_OUTPUT.NEW_LINE;
	END LOOP;
END;
/