ACCEPT NUM PROMPT '숫자 입력?'

BEGIN
	IF MOD(&NUM,15) =0  THEN
		DBMS_OUTPUT.PUT_LINE('3과 5의 공배수');
	ELSIF MOD(&NUM,3) = 0 THEN
		DBMS_OUTPUT.PUT_LINE('3의 배수');
	ELSIF MOD(&NUM,5) = 0  THEN
		DBMS_OUTPUT.PUT_LINE('5의 배수');
	ELSE
		DBMS_OUTPUT.PUT_LINE('3과 5의 배수가 아니다');
	END IF;
END;
/