ACCEPT ID PROMPT '아이디?'
ACCEPT NAME PROMPT '이름?'

DECLARE
	ID_ MEMBER.ID%TYPE := '&ID';
	NAME_ MEMBER.NAME%TYPE := '&NAME';
BEGIN
	INSERT INTO MEMBER(ID,NAME) 
	VALUES (ID_, NAME_);
	
	IF SQL%FOUND THEN
		DBMS_OUTPUT.PUT_LINE( SQL%ROWCOUNT || '행이 입력되었어요' );
		COMMIT;
	END IF;

	EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE( '오류 발생 : '|| SQLERRM );
END;
/