----------[사용자 생성및 권한]----------
--CREATE USER 아이디 IDENTIFIED BY 암호
create user user01 identified by user01; --사용자 생성
grant connect, resource to user01; -- 권한 부여

CREATE USER USER02 IDENTIFIED BY USER02; --사용자 생성
--권한부여
GRANT CREATE SESSION TO USER02;
GRANT CREATE TABLE TO USER02;
--시스템 권한 확인
SELECT * FROM SYSTEM_PRIVILEGE_MAP;
--테이블과 관련된 권한
SELECT * FROM TABLE_PRIVILEGE_MAP;

ALTER USER  USER02 QUOTA  1M On Users; --테이블 스페이스 할당

ALTER USER USER02 IDENTIFIED BY 1234; -- 비밀번호 변경

ALTER USER SCOTT ACCOUNT LOCK; -- 계정 잠구기

ALTER USER SCOTT ACCOUNT UNLOCK IDENTIFIED BY 1234; -- 계정 잠금해제 와 비밀번호 변경

DROP USER USER02 CASCADE; -- USER 삭제

CREATE ROLE USERROLE;   -- ROLE 생성
GRANT CONNECT, RESOURCE TO USERROLE;    --ROLE에 권한 부여

CREATE USER USER03 IDENTIFIED BY USER03;
GRANT USERROLE TO USER03;

CREATE USER USER04 IDENTIFIED BY USER04;
GRANT CONNECT, RESOURCE TO USER04;

GRANT SELECT ON SCOTT.EMP TO USER04; --다른 사용자의 테이블을 검색하게 권한 부여

GRANT CREATE VIEW TO USER04;
REVOKE CREATE VIEW FROM USER04;  -- 권한 제거 
